on:
  push:
    branches:
      - "main"
name: "Continuous Integration"

jobs:
  run-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
      - name: "Setup Python 3.8"
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: "Install Tox"
        run: "python -m pip install tox"
      - name: "Run Tests"
        run: tox